# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param x0 Initial value
#' @param n A given value
#' @param a A given value
#' @param b A given value
#' @return a random sample of size \code{n} 
#' @examples
#' \dontrun{
#' Y<-GibbsC(N, x0, n, a, b)
#' plot(Y[1001:N,1],Y[1001:N,2],xlab = "y1",ylab = "y2")
#' }
#' @export
GibbsC <- function(N, x0, n, a, b) {
    .Call('_StatComp21068_GibbsC', PACKAGE = 'StatComp21068', N, x0, n, a, b)
}

